sudo: required
language: cpp

compiler:
    - gcc

install:
    - pushd /tmp
    - git clone https://github.com/google/googletest.git
    - cd googletest/
    - cmake . && sudo make install

script: 
    - popd
    - cmake .
    - make -j4
    - sudo make install
    - g++ -o runtest test/* -lfsw -lgtest -lpthread -std=c++11
    - export LD_LIBRARY_PATH=/usr/local/lib/
    - ./runtest

after_success:
    - 

branches:
    only:
    - dev
    - master
    - travis